version = 0.1

# 1. Your Local Sandbox Environment
[default.deploy.parameters]
stack_name = "eve-market-api-poller"
resolve_s3 = true
s3_prefix = "eve-market-api-poller"
region = "ap-northeast-1"
profile = "sandbox-admin"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BronzeBucketName=\"/eve-market/infra/bronze-bucket-name\""
image_repositories = []

# 2. The GitHub Actions Production Environment
[prod.deploy.parameters]
stack_name = "eve-market-api-poller"
region = "ap-northeast-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
parameter_overrides = "BronzeBucketName=\"/eve-market/infra/bronze-bucket-name\""
image_repositories = []
# Replace these with your actual CloudFormation outputs:
s3_bucket = "aws-sam-cli-managed-prod-pipeline--artifactsbucket-0zuhxq4a9m0t"
role_arn = "arn:aws:iam::246814138413:role/aws-sam-cli-managed-prod--CloudFormationExecutionRo-1rqGfyMBHOvQ"

[default.global.parameters]
region = "ap-northeast-1"