AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: Eve Market - API Poller Microservice

Parameters:
  BronzeBucketName:
    Type: AWS::SSM::Parameter::Value<String>
    Default: /eve-market/infra/bronze-bucket-name

Resources:
  ApiPollerFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: app.lambda_handler
      Runtime: python3.12
      Timeout: 60
      MemorySize: 256
      Environment:
        Variables:
          RAW_DATA_BUCKET: !Ref BronzeBucketName
      Policies:
        - S3CrudPolicy:
            BucketName: !Ref BronzeBucketName
      Events:
        PollerSchedule:
          Type: Schedule
          Properties:
            # Runs every hour, passing the Venal region ID to the event payload
            Schedule: rate(1 hour)
            Enabled: true
            Input: '{"region_id": "10000015"}'
